[project]
name = "authorship-attribution"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "fsspec>=2025.9.0",
    "gensim>=4.3.2",
    "lakefs>=0.14.0",
    "matplotlib>=3.10.6",
    "nltk>=3.9.2",
    "numpy>=2.2.6",
    "pandas>=2.3.2",
    "pip>=25.2",
    "rich>=14.1.0",
    "ruff>=0.14.0",
    "scikit-learn>=1.7.2",
    "scipy>=1.15.3",
    "seaborn>=0.13.2",
    "spacy>=3.8.7",
    "tensorflow>=2.20.0",
    "tensorflow-datasets>=4.9.9",
    "wordcloud>=1.9.4",
]

[tool.ruff]
target-version = "py310"
line-length = 88

# Turn on a broader rule set
lint.select = [
  "E",   # pycodestyle
  "F",   # pyflakes (undefined/unused)
  "I",   # isort (import sorting)
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
  "T10", # flake8-debugger (breakpoint/pdb)
  "T20", # flake8-print (print/pprint)
  "W",   # pycodestyle warnings
  "PL",  # pylint-inspired checks (subset)
  "PD",  # pandas-vet (pandas best practices)
]

